<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClassListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('class_lists')->truncate();

        $data = array(
            array('id' => '1','name' => '1 - A CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '2','name' => '1 - B CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '3','name' => '1 - C CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '4','name' => '1 - D CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '5','name' => '1 - E CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '6','name' => '1 - F CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '7','name' => '1 - G CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '8','name' => '1 - H CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '9','name' => '1 - I CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '10','name' => '1 - J CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '11','name' => '1 - K CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '12','name' => '1 - L CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '13','name' => '1 - M CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '14','name' => '1 - N CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '15','name' => '1 - O CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '16','name' => '1 - P CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '17','name' => '1 - Q CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '18','name' => '1 - R CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '19','name' => '1 - S CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '20','name' => '1 - T CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '21','name' => '1 - U CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '22','name' => '1 - V CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '23','name' => '1 - W CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '24','name' => '1 - X CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '25','name' => '1 - Y CLASS','gradeId' => '1','sectionId' => '1','active' => '1'),
            array('id' => '26','name' => '2 - A CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '27','name' => '2 - B CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '28','name' => '2 - C CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '29','name' => '2 - D CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '30','name' => '2 - E CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '31','name' => '2 - F CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '32','name' => '2 - G CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '33','name' => '2 - H CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '34','name' => '2 - I CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '35','name' => '2 - J CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '36','name' => '2 - K CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '37','name' => '2 - L CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '38','name' => '2 - M CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '39','name' => '2 - N CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '40','name' => '2 - O CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '41','name' => '2 - P CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '42','name' => '2 - Q CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '43','name' => '2 - R CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '44','name' => '2 - S CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '45','name' => '2 - T CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '46','name' => '2 - U CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '47','name' => '2 - V CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '48','name' => '2 - W CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '49','name' => '2 - X CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '50','name' => '2 - Y CLASS','gradeId' => '2','sectionId' => '1','active' => '1'),
            array('id' => '51','name' => '3 - A CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '52','name' => '3 - B CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '53','name' => '3 - C CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '54','name' => '3 - D CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '55','name' => '3 - E CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '56','name' => '3 - F CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '57','name' => '3 - G CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '58','name' => '3 - H CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '59','name' => '3 - I CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '60','name' => '3 - J CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '61','name' => '3 - K CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '62','name' => '3 - L CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '63','name' => '3 - M CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '64','name' => '3 - N CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '65','name' => '3 - O CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '66','name' => '3 - P CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '67','name' => '3 - Q CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '68','name' => '3 - R CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '69','name' => '3 - S CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '70','name' => '3 - T CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '71','name' => '3 - U CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '72','name' => '3 - V CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '73','name' => '3 - W CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '74','name' => '3 - X CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '75','name' => '3 - Y CLASS','gradeId' => '3','sectionId' => '1','active' => '1'),
            array('id' => '76','name' => '4 - A CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '77','name' => '4 - B CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '78','name' => '4 - C CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '79','name' => '4 - D CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '80','name' => '4 - E CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '81','name' => '4 - F CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '82','name' => '4 - G CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '83','name' => '4 - H CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '84','name' => '4 - I CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '85','name' => '4 - J CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '86','name' => '4 - K CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '87','name' => '4 - L CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '88','name' => '4 - M CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '89','name' => '4 - N CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '90','name' => '4 - O CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '91','name' => '4 - P CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '92','name' => '4 - Q CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '93','name' => '4 - R CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '94','name' => '4 - S CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '95','name' => '4 - T CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '96','name' => '4 - U CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '97','name' => '4 - V CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '98','name' => '4 - W CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '99','name' => '4 - X CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '100','name' => '4 - Y CLASS','gradeId' => '4','sectionId' => '1','active' => '1'),
            array('id' => '101','name' => '5 - A CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '102','name' => '5 - B CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '103','name' => '5 - C CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '104','name' => '5 - D CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '105','name' => '5 - E CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '106','name' => '5 - F CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '107','name' => '5 - G CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '108','name' => '5 - H CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '109','name' => '5 - I CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '110','name' => '5 - J CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '111','name' => '5 - K CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '112','name' => '5 - L CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '113','name' => '5 - M CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '114','name' => '5 - N CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '115','name' => '5 - O CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '116','name' => '5 - P CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '117','name' => '5 - Q CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '118','name' => '5 - R CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '119','name' => '5 - S CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '120','name' => '5 - T CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '121','name' => '5 - U CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '122','name' => '5 - V CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '123','name' => '5 - W CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '124','name' => '5 - X CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '125','name' => '5 - Y CLASS','gradeId' => '5','sectionId' => '1','active' => '1'),
            array('id' => '126','name' => '6 - A CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '127','name' => '6 - B CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '128','name' => '6 - C CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '129','name' => '6 - D CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '130','name' => '6 - E CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '131','name' => '6 - F CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '132','name' => '6 - G CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '133','name' => '6 - H CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '134','name' => '6 - I CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '135','name' => '6 - J CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '136','name' => '6 - K CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '137','name' => '6 - L CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '138','name' => '6 - M CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '139','name' => '6 - N CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '140','name' => '6 - O CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '141','name' => '6 - P CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '142','name' => '6 - Q CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '143','name' => '6 - R CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '144','name' => '6 - S CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '145','name' => '6 - T CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '146','name' => '6 - U CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '147','name' => '6 - V CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '148','name' => '6 - W CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '149','name' => '6 - X CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '150','name' => '6 - Y CLASS','gradeId' => '6','sectionId' => '2','active' => '1'),
            array('id' => '151','name' => '7 - A CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '152','name' => '7 - B CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '153','name' => '7 - C CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '154','name' => '7 - D CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '155','name' => '7 - E CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '156','name' => '7 - F CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '157','name' => '7 - G CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '158','name' => '7 - H CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '159','name' => '7 - I CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '160','name' => '7 - J CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '161','name' => '7 - K CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '162','name' => '7 - L CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '163','name' => '7 - M CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '164','name' => '7 - N CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '165','name' => '7 - O CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '166','name' => '7 - P CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '167','name' => '7 - Q CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '168','name' => '7 - R CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '169','name' => '7 - S CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '170','name' => '7 - T CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '171','name' => '7 - U CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '172','name' => '7 - V CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '173','name' => '7 - W CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '174','name' => '7 - X CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '175','name' => '7 - Y CLASS','gradeId' => '7','sectionId' => '2','active' => '1'),
            array('id' => '176','name' => '8 - A CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '177','name' => '8 - B CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '178','name' => '8 - C CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '179','name' => '8 - D CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '180','name' => '8 - E CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '181','name' => '8 - F CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '182','name' => '8 - G CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '183','name' => '8 - H CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '184','name' => '8 - I CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '185','name' => '8 - J CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '186','name' => '8 - K CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '187','name' => '8 - L CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '188','name' => '8 - M CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '189','name' => '8 - N CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '190','name' => '8 - O CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '191','name' => '8 - P CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '192','name' => '8 - Q CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '193','name' => '8 - R CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '194','name' => '8 - S CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '195','name' => '8 - T CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '196','name' => '8 - U CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '197','name' => '8 - V CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '198','name' => '8 - W CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '199','name' => '8 - X CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '200','name' => '8 - Y CLASS','gradeId' => '8','sectionId' => '2','active' => '1'),
            array('id' => '201','name' => '9 - A CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '202','name' => '9 - B CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '203','name' => '9 - C CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '204','name' => '9 - D CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '205','name' => '9 - E CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '206','name' => '9 - F CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '207','name' => '9 - G CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '208','name' => '9 - H CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '209','name' => '9 - I CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '210','name' => '9 - J CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '211','name' => '9 - K CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '212','name' => '9 - L CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '213','name' => '9 - M CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '214','name' => '9 - N CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '215','name' => '9 - O CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '216','name' => '9 - P CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '217','name' => '9 - Q CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '218','name' => '9 - R CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '219','name' => '9 - S CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '220','name' => '9 - T CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '221','name' => '9 - U CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '222','name' => '9 - V CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '223','name' => '9 - W CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '224','name' => '9 - X CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '225','name' => '9 - Y CLASS','gradeId' => '9','sectionId' => '2','active' => '1'),
            array('id' => '226','name' => '10 - A CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '227','name' => '10 - B CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '228','name' => '10 - C CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '229','name' => '10 - D CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '230','name' => '10 - E CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '231','name' => '10 - F CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '232','name' => '10 - G CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '233','name' => '10 - H CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '234','name' => '10 - I CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '235','name' => '10 - J CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '236','name' => '10 - K CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '237','name' => '10 - L CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '238','name' => '10 - M CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '239','name' => '10 - N CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '240','name' => '10 - O CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '241','name' => '10 - P CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '242','name' => '10 - Q CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '243','name' => '10 - R CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '244','name' => '10 - S CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '245','name' => '10 - T CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '246','name' => '10 - U CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '247','name' => '10 - V CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '248','name' => '10 - W CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '249','name' => '10 - X CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '250','name' => '10 - Y CLASS','gradeId' => '10','sectionId' => '2','active' => '1'),
            array('id' => '251','name' => '11 - A CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '252','name' => '11 - B CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '253','name' => '11 - C CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '254','name' => '11 - D CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '255','name' => '11 - E CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '256','name' => '11 - F CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '257','name' => '11 - G CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '258','name' => '11 - H CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '259','name' => '11 - I CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '260','name' => '11 - J CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '261','name' => '11 - K CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '262','name' => '11 - L CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '263','name' => '11 - M CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '264','name' => '11 - N CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '265','name' => '11 - O CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '266','name' => '11 - P CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '267','name' => '11 - Q CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '268','name' => '11 - R CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '269','name' => '11 - S CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '270','name' => '11 - T CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '271','name' => '11 - U CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '272','name' => '11 - V CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '273','name' => '11 - W CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '274','name' => '11 - X CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '275','name' => '11 - Y CLASS','gradeId' => '11','sectionId' => '2','active' => '1'),
            array('id' => '276','name' => '12 - A ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '277','name' => '12 - B ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '278','name' => '12 - C ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '279','name' => '12 - D ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '280','name' => '12 - E ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '281','name' => '12 - F ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '282','name' => '12 - G ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '283','name' => '12 - H ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '284','name' => '12 - I ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '285','name' => '12 - J ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '286','name' => '12 - K ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '287','name' => '12 - L ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '288','name' => '12 - M ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '289','name' => '12 - N ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '290','name' => '12 - O ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '291','name' => '12 - P ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '292','name' => '12 - Q ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '293','name' => '12 - R ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '294','name' => '12 - S ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '295','name' => '12 - T ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '296','name' => '12 - U ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '297','name' => '12 - V ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '298','name' => '12 - W ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '299','name' => '12 - X ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '300','name' => '12 - Y ART CLASS','gradeId' => '12','sectionId' => '3','active' => '1'),
            array('id' => '326','name' => '12 - A SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '327','name' => '12 - B SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '328','name' => '12 - C SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '329','name' => '12 - D SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '330','name' => '12 - E SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '331','name' => '12 - F SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '332','name' => '12 - G SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '333','name' => '12 - H SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '334','name' => '12 - I SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '335','name' => '12 - J SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '336','name' => '12 - K SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '337','name' => '12 - L SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '338','name' => '12 - M SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '339','name' => '12 - N SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '340','name' => '12 - O SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '341','name' => '12 - P SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '342','name' => '12 - Q SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '343','name' => '12 - R SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '344','name' => '12 - S SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '345','name' => '12 - T SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '346','name' => '12 - U SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '347','name' => '12 - V SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '348','name' => '12 - W SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '349','name' => '12 - X SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '350','name' => '12 - Y SCIENCE CLASS','gradeId' => '12','sectionId' => '5','active' => '1'),
            array('id' => '401','name' => '13 - A ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '402','name' => '13 - B ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '403','name' => '13 - C ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '404','name' => '13 - D ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '405','name' => '13 - E ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '406','name' => '13 - F ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '407','name' => '13 - G ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '408','name' => '13 - H ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '409','name' => '13 - I ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '410','name' => '13 - J ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '411','name' => '13 - K ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '412','name' => '13 - L ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '413','name' => '13 - M ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '414','name' => '13 - N ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '415','name' => '13 - O ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '416','name' => '13 - P ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '417','name' => '13 - Q ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '418','name' => '13 - R ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '419','name' => '13 - S ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '420','name' => '13 - T ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '421','name' => '13 - U ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '422','name' => '13 - V ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '423','name' => '13 - W ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '424','name' => '13 - X ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '425','name' => '13 - Y ART CLASS','gradeId' => '13','sectionId' => '3','active' => '1'),
            array('id' => '451','name' => '13 - A SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '452','name' => '13 - B SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '453','name' => '13 - C SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '454','name' => '13 - D SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '455','name' => '13 - E SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '456','name' => '13 - F SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '457','name' => '13 - G SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '458','name' => '13 - H SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '459','name' => '13 - I SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '460','name' => '13 - J SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '461','name' => '13 - K SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '462','name' => '13 - L SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '463','name' => '13 - M SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '464','name' => '13 - N SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '465','name' => '13 - O SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '466','name' => '13 - P SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '467','name' => '13 - Q SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '468','name' => '13 - R SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '469','name' => '13 - S SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '470','name' => '13 - T SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '471','name' => '13 - U SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '472','name' => '13 - V SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '473','name' => '13 - W SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '474','name' => '13 - X SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '475','name' => '13 - Y SCIENCE CLASS','gradeId' => '13','sectionId' => '5','active' => '1'),
            array('id' => '301','name' => '12 - A COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '302','name' => '12 - B COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '303','name' => '12 - C COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '304','name' => '12 - D COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '305','name' => '12 - E COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '306','name' => '12 - F COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '307','name' => '12 - G COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '308','name' => '12 - H COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '309','name' => '12 - I COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '310','name' => '12 - J COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '311','name' => '12 - K COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '312','name' => '12 - L COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '313','name' => '12 - M COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '314','name' => '12 - N COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '315','name' => '12 - O COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '316','name' => '12 - P COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '317','name' => '12 - Q COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '318','name' => '12 - R COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '319','name' => '12 - S COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '320','name' => '12 - T COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '321','name' => '12 - U COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '322','name' => '12 - V COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '323','name' => '12 - W COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '324','name' => '12 - X COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '325','name' => '12 - Y COMMERCE CLASS','gradeId' => '12','sectionId' => '4','active' => '1'),
            array('id' => '351','name' => '12 - A TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '352','name' => '12 - B TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '353','name' => '12 - C TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '354','name' => '12 - D TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '355','name' => '12 - E TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '356','name' => '12 - F TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '357','name' => '12 - G TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '358','name' => '12 - H TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '359','name' => '12 - I TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '360','name' => '12 - J TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '361','name' => '12 - K TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '362','name' => '12 - L TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '363','name' => '12 - M TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '364','name' => '12 - N TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '365','name' => '12 - O TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '366','name' => '12 - P TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '367','name' => '12 - Q TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '368','name' => '12 - R TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '369','name' => '12 - S TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '370','name' => '12 - T TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '371','name' => '12 - U TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '372','name' => '12 - V TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '373','name' => '12 - W TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '374','name' => '12 - X TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '375','name' => '12 - Y TECHNOLOGY CLASS','gradeId' => '12','sectionId' => '6','active' => '1'),
            array('id' => '376','name' => '12 - A 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '377','name' => '12 - B 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '378','name' => '12 - C 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '379','name' => '12 - D 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '380','name' => '12 - E 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '381','name' => '12 - F 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '382','name' => '12 - G 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '383','name' => '12 - H 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '384','name' => '12 - I 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '385','name' => '12 - J 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '386','name' => '12 - K 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '387','name' => '12 - L 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '388','name' => '12 - M 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '389','name' => '12 - N 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '390','name' => '12 - O 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '391','name' => '12 - P 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '392','name' => '12 - Q 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '393','name' => '12 - R 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '394','name' => '12 - S 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '395','name' => '12 - T 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '396','name' => '12 - U 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '397','name' => '12 - V 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '398','name' => '12 - W 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '399','name' => '12 - X 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '400','name' => '12 - Y 13 YEARS CLASS','gradeId' => '12','sectionId' => '7','active' => '1'),
            array('id' => '426','name' => '13 - A COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '427','name' => '13 - B COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '428','name' => '13 - C COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '429','name' => '13 - D COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '430','name' => '13 - E COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '431','name' => '13 - F COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '432','name' => '13 - G COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '433','name' => '13 - H COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '434','name' => '13 - I COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '435','name' => '13 - J COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '436','name' => '13 - K COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '437','name' => '13 - L COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '438','name' => '13 - M COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '439','name' => '13 - N COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '440','name' => '13 - O COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '441','name' => '13 - P COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '442','name' => '13 - Q COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '443','name' => '13 - R COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '444','name' => '13 - S COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '445','name' => '13 - T COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '446','name' => '13 - U COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '447','name' => '13 - V COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '448','name' => '13 - W COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '449','name' => '13 - X COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '450','name' => '13 - Y COMMERCE CLASS','gradeId' => '13','sectionId' => '4','active' => '1'),
            array('id' => '476','name' => '13 - A TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '477','name' => '13 - B TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '478','name' => '13 - C TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '479','name' => '13 - D TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '480','name' => '13 - E TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '481','name' => '13 - F TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '482','name' => '13 - G TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '483','name' => '13 - H TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '484','name' => '13 - I TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '485','name' => '13 - J TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '486','name' => '13 - K TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '487','name' => '13 - L TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '488','name' => '13 - M TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '489','name' => '13 - N TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '490','name' => '13 - O TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '491','name' => '13 - P TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '492','name' => '13 - Q TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '493','name' => '13 - R TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '494','name' => '13 - S TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '495','name' => '13 - T TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '496','name' => '13 - U TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '497','name' => '13 - V TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '498','name' => '13 - W TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '499','name' => '13 - X TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '500','name' => '13 - Y TECHNOLOGY CLASS','gradeId' => '13','sectionId' => '6','active' => '1'),
            array('id' => '501','name' => '13 - A 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '502','name' => '13 - B 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '503','name' => '13 - C 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '504','name' => '13 - D 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '505','name' => '13 - E 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '506','name' => '13 - F 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '507','name' => '13 - G 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '508','name' => '13 - H 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '509','name' => '13 - I 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '510','name' => '13 - J 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '511','name' => '13 - K 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '512','name' => '13 - L 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '513','name' => '13 - M 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '514','name' => '13 - N 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '515','name' => '13 - O 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '516','name' => '13 - P 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '517','name' => '13 - Q 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '518','name' => '13 - R 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '519','name' => '13 - S 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '520','name' => '13 - T 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '521','name' => '13 - U 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '522','name' => '13 - V 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '523','name' => '13 - W 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '524','name' => '13 - X 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '525','name' => '13 - Y 13 YEARS CLASS','gradeId' => '13','sectionId' => '7','active' => '1'),
            array('id' => '526','name' => 'SPECIAL EDUCATION - A CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '527','name' => 'SPECIAL EDUCATION - B CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '528','name' => 'SPECIAL EDUCATION - C CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '529','name' => 'SPECIAL EDUCATION - D CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '530','name' => 'SPECIAL EDUCATION - E CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '531','name' => 'SPECIAL EDUCATION - F CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '532','name' => 'SPECIAL EDUCATION - G CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '533','name' => 'SPECIAL EDUCATION - H CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '534','name' => 'SPECIAL EDUCATION - I CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '535','name' => 'SPECIAL EDUCATION - J CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '536','name' => 'SPECIAL EDUCATION - K CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '537','name' => 'SPECIAL EDUCATION - L CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '538','name' => 'SPECIAL EDUCATION - M CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '539','name' => 'SPECIAL EDUCATION - N CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '540','name' => 'SPECIAL EDUCATION - O CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '541','name' => 'SPECIAL EDUCATION - P CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '542','name' => 'SPECIAL EDUCATION - Q CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '543','name' => 'SPECIAL EDUCATION - R CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '544','name' => 'SPECIAL EDUCATION - S CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '545','name' => 'SPECIAL EDUCATION - T CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '546','name' => 'SPECIAL EDUCATION - U CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '547','name' => 'SPECIAL EDUCATION - V CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '548','name' => 'SPECIAL EDUCATION - W CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '549','name' => 'SPECIAL EDUCATION - X CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
            array('id' => '550','name' => 'SPECIAL EDUCATION - Y CLASS','gradeId' => '0','sectionId' => '8','active' => '1'),
        );

        DB::table('class_lists')->insert($data);
    }
}
