<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DsDivisionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ds_divisions')->truncate();

        $data = array(
            array('id' => '1','name' => 'Vavuniya North','districtId' => '10'),
            array('id' => '2','name' => 'Vavuniya','districtId' => '10'),
            array('id' => '3','name' => 'Vavuniya South','districtId' => '10'),
            array('id' => '4','name' => 'Vengalacheddiculam','districtId' => '10'),
            array('id' => '5','name' => 'Kuchaveli','districtId' => '4'),
            array('id' => '6','name' => 'Gomarankadawela','districtId' => '4'),
            array('id' => '7','name' => 'Morawewa','districtId' => '4'),
            array('id' => '8','name' => 'Town & Gravets','districtId' => '4'),
            array('id' => '9','name' => 'Kinniya','districtId' => '4'),
            array('id' => '10','name' => 'Thampalakamam','districtId' => '4'),
            array('id' => '11','name' => 'Muttur','districtId' => '4'),
            array('id' => '12','name' => 'Kantalai','districtId' => '4'),
            array('id' => '13','name' => 'Seruvila','districtId' => '4'),
            array('id' => '14','name' => 'Eachchilampattai','districtId' => '4'),
            array('id' => '15','name' => 'Padavi Sri Pura','districtId' => '4'),
            array('id' => '16','name' => 'Kolonna','districtId' => '15'),
            array('id' => '17','name' => 'Embilipitiya','districtId' => '15'),
            array('id' => '18','name' => 'Weligepola','districtId' => '15'),
            array('id' => '19','name' => 'Kalawana','districtId' => '15'),
            array('id' => '20','name' => 'Nivithigala','districtId' => '15'),
            array('id' => '21','name' => 'Rathnapura','districtId' => '15'),
            array('id' => '22','name' => 'Pelmadulla','districtId' => '15'),
            array('id' => '23','name' => 'Opanayaka','districtId' => '15'),
            array('id' => '24','name' => 'Kuruwita','districtId' => '15'),
            array('id' => '25','name' => 'Kiriella','districtId' => '15'),
            array('id' => '26','name' => 'Kahawaththa','districtId' => '15'),
            array('id' => '27','name' => 'Imbulpe','districtId' => '15'),
            array('id' => '28','name' => 'Godakawela','districtId' => '15'),
            array('id' => '29','name' => 'Elapatha','districtId' => '15'),
            array('id' => '30','name' => 'Eheliyagoda','districtId' => '15'),
            array('id' => '31','name' => 'Ayagama','districtId' => '15'),
            array('id' => '32','name' => 'Balangoda','districtId' => '15'),
            array('id' => '33','name' => 'Nattandiya','districtId' => '8'),
            array('id' => '34','name' => 'Vanathavilluwa','districtId' => '8'),
            array('id' => '35','name' => 'Kalpitiya','districtId' => '8'),
            array('id' => '36','name' => 'Mundalama','districtId' => '8'),
            array('id' => '37','name' => 'Mahakumbukkadawala','districtId' => '8'),
            array('id' => '38','name' => 'Anamaduwa','districtId' => '8'),
            array('id' => '39','name' => 'Wennappuwa','districtId' => '8'),
            array('id' => '40','name' => 'Puttalam','districtId' => '8'),
            array('id' => '41','name' => 'Karuwalagaswewa','districtId' => '8'),
            array('id' => '42','name' => 'Nawagattegama','districtId' => '8'),
            array('id' => '43','name' => 'Arachchikattuwa','districtId' => '8'),
            array('id' => '44','name' => 'Chilaw','districtId' => '8'),
            array('id' => '45','name' => 'Madampe','districtId' => '8'),
            array('id' => '46','name' => 'Dankotuwa','districtId' => '8'),
            array('id' => '47','name' => 'Mahawewa','districtId' => '8'),
            array('id' => '48','name' => 'Pallama','districtId' => '8'),
            array('id' => '49','name' => 'Medirigiriya','districtId' => '6'),
            array('id' => '50','name' => 'Elahera','districtId' => '6'),
            array('id' => '51','name' => 'Lankapura','districtId' => '6'),
            array('id' => '52','name' => 'Dimbulagala','districtId' => '6'),
            array('id' => '53','name' => 'Hingurakgoda','districtId' => '6'),
            array('id' => '54','name' => 'Thamankaduwa','districtId' => '6'),
            array('id' => '55','name' => 'Welikanda','districtId' => '6'),
            array('id' => '56','name' => 'Ambagamuwa','districtId' => '1'),
            array('id' => '57','name' => 'Hanguranketha','districtId' => '1'),
            array('id' => '58','name' => 'Kothmale','districtId' => '1'),
            array('id' => '59','name' => 'Nuwara Eliya','districtId' => '1'),
            array('id' => '60','name' => 'Walapane','districtId' => '1'),
            array('id' => '61','name' => 'Tunukkai','districtId' => '11'),
            array('id' => '62','name' => 'Pudukudiyirippu','districtId' => '11'),
            array('id' => '63','name' => 'Maritimepattu','districtId' => '11'),
            array('id' => '64','name' => 'Mathai East','districtId' => '11'),
            array('id' => '65','name' => 'Wellawaya','districtId' => '24'),
            array('id' => '66','name' => 'Thanamalwila','districtId' => '24'),
            array('id' => '67','name' => 'Siyambalanduwa','districtId' => '24'),
            array('id' => '68','name' => 'Sewanagala','districtId' => '24'),
            array('id' => '69','name' => 'Moneragala','districtId' => '24'),
            array('id' => '70','name' => 'Medagama','districtId' => '24'),
            array('id' => '71','name' => 'Katharagama','districtId' => '24'),
            array('id' => '72','name' => 'Madulla','districtId' => '24'),
            array('id' => '73','name' => 'Buttala','districtId' => '24'),
            array('id' => '74','name' => 'Bibila','districtId' => '24'),
            array('id' => '75','name' => 'Badalkumbura','districtId' => '24'),
            array('id' => '76','name' => 'Kotapola','districtId' => '17'),
            array('id' => '77','name' => 'Pasgoda','districtId' => '17'),
            array('id' => '78','name' => 'Pitabeddara','districtId' => '17'),
            array('id' => '79','name' => 'Mulatiyana','districtId' => '17'),
            array('id' => '80','name' => 'Akuressa','districtId' => '17'),
            array('id' => '81','name' => 'Athuraliya','districtId' => '17'),
            array('id' => '82','name' => 'Hakmana','districtId' => '17'),
            array('id' => '83','name' => 'Kamburupitiya','districtId' => '17'),
            array('id' => '84','name' => 'Kirinda Puhulwella','districtId' => '17'),
            array('id' => '85','name' => 'Malimbada','districtId' => '17'),
            array('id' => '86','name' => 'Welipitiya','districtId' => '17'),
            array('id' => '87','name' => 'Thihagoda','districtId' => '17'),
            array('id' => '88','name' => 'Devinuwara','districtId' => '17'),
            array('id' => '89','name' => 'Dickwella','districtId' => '17'),
            array('id' => '90','name' => 'Weligama','districtId' => '17'),
            array('id' => '91','name' => 'Matara Four Gravets','districtId' => '17'),
            array('id' => '92','name' => 'Yatawatta','districtId' => '2'),
            array('id' => '93','name' => 'Ambanganga Koralaya','districtId' => '2'),
            array('id' => '94','name' => 'Dambulla','districtId' => '2'),
            array('id' => '95','name' => 'Wilgamuwa','districtId' => '2'),
            array('id' => '96','name' => 'Matale','districtId' => '2'),
            array('id' => '97','name' => 'Laggala-Pallegama','districtId' => '2'),
            array('id' => '98','name' => 'Naula','districtId' => '2'),
            array('id' => '99','name' => 'Pallepola','districtId' => '2'),
            array('id' => '100','name' => 'Galewela','districtId' => '2'),
            array('id' => '101','name' => 'Rattota','districtId' => '2'),
            array('id' => '102','name' => 'Ukuwela','districtId' => '2'),
            array('id' => '103','name' => 'Mannar Town','districtId' => '12'),
            array('id' => '104','name' => 'Manthai West','districtId' => '12'),
            array('id' => '105','name' => 'Musalai','districtId' => '12'),
            array('id' => '106','name' => 'Madhu','districtId' => '12'),
            array('id' => '107','name' => 'Nanaddan','districtId' => '12'),
            array('id' => '108','name' => 'Giribawa','districtId' => '9'),
            array('id' => '109','name' => 'Galgamuwa','districtId' => '9'),
            array('id' => '110','name' => 'Ehetuwewa','districtId' => '9'),
            array('id' => '111','name' => 'Ambanpola','districtId' => '9'),
            array('id' => '112','name' => 'Polpithigama','districtId' => '9'),
            array('id' => '113','name' => 'Kotawehera','districtId' => '9'),
            array('id' => '114','name' => 'Ganewatta','districtId' => '9'),
            array('id' => '115','name' => 'Ibbagamuwa','districtId' => '9'),
            array('id' => '116','name' => 'Mahawa','districtId' => '9'),
            array('id' => '117','name' => 'Kurunegala','districtId' => '9'),
            array('id' => '118','name' => 'Nikaweratiya','districtId' => '9'),
            array('id' => '119','name' => 'Pannala','districtId' => '9'),
            array('id' => '120','name' => 'Udubaddawa','districtId' => '9'),
            array('id' => '121','name' => 'Bingiriya','districtId' => '9'),
            array('id' => '122','name' => 'Kuliyapitiya West','districtId' => '9'),
            array('id' => '123','name' => 'Kuliyapitiya East','districtId' => '9'),
            array('id' => '124','name' => 'Rasnayakapura','districtId' => '9'),
            array('id' => '125','name' => 'Weerambugedara','districtId' => '9'),
            array('id' => '126','name' => 'Alawwa','districtId' => '9'),
            array('id' => '127','name' => 'Narammala','districtId' => '9'),
            array('id' => '128','name' => 'Bamunukotuwa','districtId' => '9'),
            array('id' => '129','name' => 'Katupotha','districtId' => '9'),
            array('id' => '130','name' => 'Panduwasnuwara','districtId' => '9'),
            array('id' => '131','name' => 'Kobeigane','districtId' => '9'),
            array('id' => '132','name' => 'Maspotha','districtId' => '9'),
            array('id' => '133','name' => 'Mallawapitiya','districtId' => '9'),
            array('id' => '134','name' => 'Rideegama','districtId' => '9'),
            array('id' => '135','name' => 'Wariyapola','districtId' => '9'),
            array('id' => '136','name' => 'Mawathagama','districtId' => '9'),
            array('id' => '137','name' => 'Polgahawela','districtId' => '9'),
            array('id' => '138','name' => 'Karachchi','districtId' => '13'),
            array('id' => '139','name' => 'Poonakary','districtId' => '13'),
            array('id' => '140','name' => 'Pachchilaipalli','districtId' => '13'),
            array('id' => '141','name' => 'Dehiovita','districtId' => '16'),
            array('id' => '142','name' => 'Ruwanwella','districtId' => '16'),
            array('id' => '143','name' => 'Yatiyanthota','districtId' => '16'),
            array('id' => '144','name' => 'Deraniyagala','districtId' => '16'),
            array('id' => '145','name' => 'Warakapola','districtId' => '16'),
            array('id' => '146','name' => 'Galigamuwa','districtId' => '16'),
            array('id' => '147','name' => 'Bulathkohupitiya','districtId' => '16'),
            array('id' => '148','name' => 'Rambukkana','districtId' => '16'),
            array('id' => '149','name' => 'Kegalle','districtId' => '16'),
            array('id' => '150','name' => 'Mawanella','districtId' => '16'),
            array('id' => '151','name' => 'Aranayaka','districtId' => '16'),
            array('id' => '152','name' => 'Minipe','districtId' => '3'),
            array('id' => '153','name' => 'Udunuwara','districtId' => '3'),
            array('id' => '154','name' => 'Hatharaliyadda','districtId' => '3'),
            array('id' => '155','name' => 'Poojapitiya','districtId' => '3'),
            array('id' => '156','name' => 'Thumpane','districtId' => '3'),
            array('id' => '157','name' => 'Akurana','districtId' => '3'),
            array('id' => '158','name' => 'Ganga Ihala Korale','districtId' => '3'),
            array('id' => '159','name' => 'Udadumbara','districtId' => '3'),
            array('id' => '160','name' => 'Udapalatha','districtId' => '3'),
            array('id' => '161','name' => 'Delthota','districtId' => '3'),
            array('id' => '162','name' => 'Pasbage Korale','districtId' => '3'),
            array('id' => '163','name' => 'Medadumbara','districtId' => '3'),
            array('id' => '164','name' => 'Pathadumbara','districtId' => '3'),
            array('id' => '165','name' => 'Panwila','districtId' => '3'),
            array('id' => '166','name' => 'Harispattuwa','districtId' => '3'),
            array('id' => '167','name' => 'Yatinuwara','districtId' => '3'),
            array('id' => '168','name' => 'Doluwa','districtId' => '3'),
            array('id' => '169','name' => 'Pathahewaheta','districtId' => '3'),
            array('id' => '170','name' => 'Kundasale','districtId' => '3'),
            array('id' => '171','name' => 'Gangawata Korale','districtId' => '3'),
            array('id' => '172','name' => 'Panadura','districtId' => '21'),
            array('id' => '173','name' => 'Horana','districtId' => '21'),
            array('id' => '174','name' => 'Ingiriya','districtId' => '21'),
            array('id' => '175','name' => 'Agalawatta','districtId' => '21'),
            array('id' => '176','name' => 'Walallawita','districtId' => '21'),
            array('id' => '177','name' => 'Palindanuwara','districtId' => '21'),
            array('id' => '178','name' => 'Mathugama','districtId' => '21'),
            array('id' => '179','name' => 'Beruwala','districtId' => '21'),
            array('id' => '180','name' => 'Bulathsinhala','districtId' => '21'),
            array('id' => '181','name' => 'Dodangoda','districtId' => '21'),
            array('id' => '182','name' => 'Millaniya','districtId' => '21'),
            array('id' => '183','name' => 'Bandaragama','districtId' => '21'),
            array('id' => '184','name' => 'Kaluthara','districtId' => '21'),
            array('id' => '185','name' => 'Madurawala','districtId' => '21'),
            array('id' => '186','name' => 'Chankanai','districtId' => '14'),
            array('id' => '187','name' => 'Sandilipay','districtId' => '14'),
            array('id' => '188','name' => 'Tellipallai','districtId' => '14'),
            array('id' => '189','name' => 'Uduvil','districtId' => '14'),
            array('id' => '190','name' => 'Nallur','districtId' => '14'),
            array('id' => '191','name' => 'Jaffna','districtId' => '14'),
            array('id' => '192','name' => 'Kopay','districtId' => '14'),
            array('id' => '193','name' => 'Velanai','districtId' => '14'),
            array('id' => '194','name' => 'Kayts','districtId' => '14'),
            array('id' => '195','name' => 'Point Pedro','districtId' => '14'),
            array('id' => '196','name' => 'Karaveddy','districtId' => '14'),
            array('id' => '197','name' => 'Chavakachcheri','districtId' => '14'),
            array('id' => '198','name' => 'Delft','districtId' => '14'),
            array('id' => '199','name' => 'Maruthnkerny','districtId' => '14'),
            array('id' => '200','name' => 'Tangalle','districtId' => '18'),
            array('id' => '201','name' => 'Ambalantota','districtId' => '18'),
            array('id' => '202','name' => 'Weeraketiya','districtId' => '18'),
            array('id' => '203','name' => 'Walasmulla','districtId' => '18'),
            array('id' => '204','name' => 'Katuwana','districtId' => '18'),
            array('id' => '205','name' => 'Angunukolapelessa','districtId' => '18'),
            array('id' => '206','name' => 'Okewela','districtId' => '18'),
            array('id' => '207','name' => 'Beliatta','districtId' => '18'),
            array('id' => '208','name' => 'Tissamaharama','districtId' => '18'),
            array('id' => '209','name' => 'Lunugamvehera','districtId' => '18'),
            array('id' => '210','name' => 'Sooriyawewa','districtId' => '18'),
            array('id' => '211','name' => 'Hambantota','districtId' => '18'),
            array('id' => '212','name' => 'Wattala','districtId' => '22'),
            array('id' => '213','name' => 'Kelaniya','districtId' => '22'),
            array('id' => '214','name' => 'Mahara','districtId' => '22'),
            array('id' => '215','name' => 'Biyagama','districtId' => '22'),
            array('id' => '216','name' => 'Dompe','districtId' => '22'),
            array('id' => '217','name' => 'Attanagalla','districtId' => '22'),
            array('id' => '218','name' => 'Gampaha','districtId' => '22'),
            array('id' => '219','name' => 'Minuwangoda','districtId' => '22'),
            array('id' => '220','name' => 'Divulapitiya','districtId' => '22'),
            array('id' => '221','name' => 'Mirigama','districtId' => '22'),
            array('id' => '222','name' => 'Katana','districtId' => '22'),
            array('id' => '223','name' => 'Ja-Ela','districtId' => '22'),
            array('id' => '224','name' => 'Negombo','districtId' => '22'),
            array('id' => '225','name' => 'Akmeemana','districtId' => '19'),
            array('id' => '226','name' => 'Ambalangoda','districtId' => '19'),
            array('id' => '227','name' => 'Baddegama','districtId' => '19'),
            array('id' => '228','name' => 'Balapitiya','districtId' => '19'),
            array('id' => '229','name' => 'Bentota','districtId' => '19'),
            array('id' => '230','name' => 'Bope-Poddala','districtId' => '19'),
            array('id' => '231','name' => 'Elpitiya','districtId' => '19'),
            array('id' => '232','name' => 'Galle Four Gravets','districtId' => '19'),
            array('id' => '233','name' => 'Habaraduwa','districtId' => '19'),
            array('id' => '234','name' => 'Hikkaduwa','districtId' => '19'),
            array('id' => '235','name' => 'Karandeniya','districtId' => '19'),
            array('id' => '236','name' => 'Nagoda','districtId' => '19'),
            array('id' => '237','name' => 'Neluwa','districtId' => '19'),
            array('id' => '238','name' => 'Niyagama','districtId' => '19'),
            array('id' => '239','name' => 'Thawalama','districtId' => '19'),
            array('id' => '240','name' => 'Welivitiya-Divithura','districtId' => '19'),
            array('id' => '241','name' => 'Yakkalamulla','districtId' => '19'),
            array('id' => '242','name' => 'Imaduwa','districtId' => '19'),
            array('id' => '243','name' => 'Padukka','districtId' => '23'),
            array('id' => '244','name' => 'Homagama','districtId' => '23'),
            array('id' => '245','name' => 'Hanwella','districtId' => '23'),
            array('id' => '246','name' => 'Dehiwala','districtId' => '23'),
            array('id' => '247','name' => 'Kesbewa','districtId' => '23'),
            array('id' => '248','name' => 'Maharagama','districtId' => '23'),
            array('id' => '249','name' => 'Kolonnawa','districtId' => '23'),
            array('id' => '250','name' => 'Colombo','districtId' => '23'),
            array('id' => '251','name' => 'Rathmalana','districtId' => '23'),
            array('id' => '252','name' => 'Moratuwa','districtId' => '23'),
            array('id' => '253','name' => 'Thimbirigasyaya','districtId' => '23'),
            array('id' => '254','name' => 'Sri Jayawardanapura Kotte','districtId' => '23'),
            array('id' => '255','name' => 'Kaduwela','districtId' => '23'),
            array('id' => '256','name' => 'Koralai Pattu (Valach.)','districtId' => '5'),
            array('id' => '257','name' => 'Koralai P. W. (Oddamavadi)','districtId' => '5'),
            array('id' => '258','name' => 'Manmunai S. and Eruvilpattu','districtId' => '5'),
            array('id' => '259','name' => 'Koralai Pattu North','districtId' => '5'),
            array('id' => '260','name' => 'Manmunai North','districtId' => '5'),
            array('id' => '261','name' => 'Manmunai West','districtId' => '5'),
            array('id' => '262','name' => 'Manmunai South - West','districtId' => '5'),
            array('id' => '263','name' => 'Porativu Pattu','districtId' => '5'),
            array('id' => '264','name' => 'Manmunai P. (Araipattai)','districtId' => '5'),
            array('id' => '265','name' => 'Eravur Town','districtId' => '5'),
            array('id' => '266','name' => 'Eravur Pattu','districtId' => '5'),
            array('id' => '267','name' => 'Kattankudy','districtId' => '5'),
            array('id' => '268','name' => 'Soranathota','districtId' => '20'),
            array('id' => '269','name' => 'Haldummulla','districtId' => '20'),
            array('id' => '270','name' => 'Kandaketiya','districtId' => '20'),
            array('id' => '271','name' => 'Mahiyanganaya','districtId' => '20'),
            array('id' => '272','name' => 'Rideemaliyadda','districtId' => '20'),
            array('id' => '273','name' => 'Welimada','districtId' => '20'),
            array('id' => '274','name' => 'Haputhale','districtId' => '20'),
            array('id' => '275','name' => 'Passara','districtId' => '20'),
            array('id' => '276','name' => 'Meegahakivula','districtId' => '20'),
            array('id' => '277','name' => 'Uva Paranagama','districtId' => '20'),
            array('id' => '278','name' => 'Hali Ela','districtId' => '20'),
            array('id' => '279','name' => 'Badulla','districtId' => '20'),
            array('id' => '280','name' => 'Ella','districtId' => '20'),
            array('id' => '281','name' => 'Bandarawela','districtId' => '20'),
            array('id' => '282','name' => 'Lunugala','districtId' => '20'),
            array('id' => '283','name' => 'Thambuttegama','districtId' => '7'),
            array('id' => '284','name' => 'Horowpothana','districtId' => '7'),
            array('id' => '285','name' => 'Maha Vilachchiya','districtId' => '7'),
            array('id' => '286','name' => 'Padaviya','districtId' => '7'),
            array('id' => '287','name' => 'Galenbidunuwawe','districtId' => '7'),
            array('id' => '288','name' => 'Galnewa','districtId' => '7'),
            array('id' => '289','name' => 'Ipalogama','districtId' => '7'),
            array('id' => '290','name' => 'Kahatagasdigiliya','districtId' => '7'),
            array('id' => '291','name' => 'Kekirawa','districtId' => '7'),
            array('id' => '292','name' => 'Thirappane','districtId' => '7'),
            array('id' => '293','name' => 'Medawachchiya','districtId' => '7'),
            array('id' => '294','name' => 'Rambewa','districtId' => '7'),
            array('id' => '295','name' => 'Mihintale','districtId' => '7'),
            array('id' => '296','name' => 'Nochchiyagama','districtId' => '7'),
            array('id' => '297','name' => 'Palugaswewa','districtId' => '7'),
            array('id' => '298','name' => 'Palagala','districtId' => '7'),
            array('id' => '299','name' => 'Kebithigollewa','districtId' => '7'),
            array('id' => '300','name' => 'Nuwaragam Palatha East','districtId' => '7'),
            array('id' => '301','name' => 'Thalawa','districtId' => '7'),
            array('id' => '302','name' => 'Rajanganaya','districtId' => '7'),
            array('id' => '303','name' => 'Nachchadoowa','districtId' => '7'),
            array('id' => '304','name' => 'Nuwaragam Palatha Central','districtId' => '7'),
            array('id' => '305','name' => 'Lahugala','districtId' => '25'),
            array('id' => '306','name' => 'Pothuvil','districtId' => '25'),
            array('id' => '307','name' => 'Thirukkovil','districtId' => '25'),
            array('id' => '308','name' => 'Damana','districtId' => '25'),
            array('id' => '309','name' => 'Alayadiwembu','districtId' => '25'),
            array('id' => '310','name' => 'Akkaraipattu','districtId' => '25'),
            array('id' => '311','name' => 'Eragama','districtId' => '25'),
            array('id' => '312','name' => 'Addalachchenai','districtId' => '25'),
            array('id' => '313','name' => 'Ninthavur','districtId' => '25'),
            array('id' => '314','name' => 'Karativu','districtId' => '25'),
            array('id' => '315','name' => 'Sainthamarathu','districtId' => '25'),
            array('id' => '316','name' => 'Kalmunai','districtId' => '25'),
            array('id' => '317','name' => 'Samanthurai','districtId' => '25'),
            array('id' => '318','name' => 'Navithanveli','districtId' => '25'),
            array('id' => '319','name' => 'Ampara','districtId' => '25'),
            array('id' => '320','name' => 'Uhana','districtId' => '25'),
            array('id' => '321','name' => 'Mahaoya','districtId' => '25'),
            array('id' => '322','name' => 'Padiyathalawa','districtId' => '25'),
            array('id' => '323','name' => 'Dehiattakandiya','districtId' => '25')
        );

        DB::table('ds_divisions')->insert($data);
    }
}
